### PR TITLE
Bundled gtest

### PR DESCRIPTION
**Pull request by deleeke**
@boyceg 

This branch has a bundled trimmed down version of googletest. 
It is not finished but I want to see if the VM can successfully build bundled gtest.

Currently this branch can:

1) link with and external build of googletest in a user specified directory
2) If only --enable-gtest is passed, it reverts to bundled googletest
        --ibtk's configure invokes googletest's configure
        -- "make" compiles libgtest and puts it in proper place in build dir much like muparser
        --currently does no checks on bundled googletest
3) Default mode is not to enable Google Test, in which case Google Test's configure is not invoked, so it doesn't break things if it is not there.

TODO:
* Pretty up formatting -- Text output during configure currently bleeds into boost checks
* Make sure googletest is not using libtool in some way that you don't want to allow
* Have OSX user try this out.
* if literally bundling some of the googletest source code (like muparser is), trim any unused portions of googletest
* try and get this to work with git submodules (if that is more desirable)
        * the challenge I see is that the directory structure of googletest is like:
googletest/
├── googletest/
│   ├── configure
│   ├── Makefile.am
│   ├── *lots of other stuff*

But make needs to know how to get in to that directory that actually has source code so I have inserted a makefile here that knows about descending to the proper level. I'm not sure how to do that if we use git submodules.

googletest/
├── Makefile.am
├── googletest/
│   ├── configure
│   ├── Makefile.am
│   ├── *lots of other stuff*

### CODE REVIEW

**Comment by deleeke** [comment]
Now the VM is attempting to build libgtest upon running "make" but has a series of problems.

Also, this output from make illustrates my concern about how libtool is being used. 
Boyce, Is googletest using libtool to do the linking? @boyceg

```
Making all in googletest
make[3]: Entering directory `/srv/jenkins_home/workspace/testFolder/DevOpTester/ibamr_pr_LLVM/ibtk/contrib/googletest'
Making all in googletest
make[4]: Entering directory `/srv/jenkins_home/workspace/testFolder/DevOpTester/ibamr_pr_LLVM/ibtk/contrib/googletest/googletest'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /srv/jenkins_home/workspace/testFolder/DevOpTester/ibamr_pr_LLVM/ibtk/contrib/googletest/googletest/build-aux/missing aclocal-1.15 -I m4
/srv/jenkins_home/workspace/testFolder/DevOpTester/ibamr_pr_LLVM/ibtk/contrib/googletest/googletest/build-aux/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[4]: *** [aclocal.m4] Error 127
make[4]: Failed to remake makefile `Makefile'.
mkdir -p "./fused-src"
depbase=`echo src/gtest-all.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/bash ./libtool  --tag=CXX   --mode=compile ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux  -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT src/gtest-all.lo -MD -MP -MF $depbase.Tpo -c -o src/gtest-all.lo src/gtest-all.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
chmod -R u+w "./fused-src"
depbase=`echo src/gtest_main.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/bash ./libtool  --tag=CXX   --mode=compile ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux  -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT src/gtest_main.lo -MD -MP -MF $depbase.Tpo -c -o src/gtest_main.lo src/gtest_main.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
depbase=`echo samples/sample2.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/bash ./libtool  --tag=CXX   --mode=compile ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux  -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT samples/sample2.lo -MD -MP -MF $depbase.Tpo -c -o samples/sample2.lo samples/sample2.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
rm -f "./fused-src/gtest/gtest-all.cc"
rm -f "./fused-src/gtest/gtest.h"
"./scripts/fuse_gtest_files.py" "./fused-src"
cp -f "./src/gtest_main.cc" "./fused-src/gtest/"
depbase=`echo samples/sample4.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/bash ./libtool  --tag=CXX   --mode=compile ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux  -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT samples/sample4.lo -MD -MP -MF $depbase.Tpo -c -o samples/sample4.lo samples/sample4.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT samples/sample2.lo -MD -MP -MF samples/.deps/sample2.Tpo -c samples/sample2.cc  -fPIC -DPIC -o samples/.libs/sample2.o
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT src/gtest_main.lo -MD -MP -MF src/.deps/gtest_main.Tpo -c src/gtest_main.cc  -fPIC -DPIC -o src/.libs/gtest_main.o
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT src/gtest-all.lo -MD -MP -MF src/.deps/gtest-all.Tpo -c src/gtest-all.cc  -fPIC -DPIC -o src/.libs/gtest-all.o
clang: warning: argument unused during compilation: '-I /srv/LLVMsfw/linux/openmpi/1.10.2/include'
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT samples/sample2.lo -MD -MP -MF samples/.deps/sample2.Tpo -c samples/sample2.cc -o samples/sample2.o >/dev/null 2>&1
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT samples/sample4.lo -MD -MP -MF samples/.deps/sample4.Tpo -c samples/sample4.cc  -fPIC -DPIC -o samples/.libs/sample4.o
depbase=`echo samples/sample1.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/bash ./libtool  --tag=CXX   --mode=compile ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux  -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT samples/sample1.lo -MD -MP -MF $depbase.Tpo -c -o samples/sample1.lo samples/sample1.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
clang: warning: argument unused during compilation: '-I /srv/LLVMsfw/linux/openmpi/1.10.2/include'
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT samples/sample4.lo -MD -MP -MF samples/.deps/sample4.Tpo -c samples/sample4.cc -o samples/sample4.o >/dev/null 2>&1
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT samples/sample1.lo -MD -MP -MF samples/.deps/sample1.Tpo -c samples/sample1.cc  -fPIC -DPIC -o samples/.libs/sample1.o
clang: warning: argument unused during compilation: '-I /srv/LLVMsfw/linux/openmpi/1.10.2/include'
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT samples/sample1.lo -MD -MP -MF samples/.deps/sample1.Tpo -c samples/sample1.cc -o samples/sample1.o >/dev/null 2>&1
/bin/bash ./libtool  --tag=CXX   --mode=link ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DGTEST_HAS_PTHREAD=1 -Wall   -o samples/libsamples.la  samples/sample1.lo samples/sample2.lo samples/sample4.lo  
clang: warning: argument unused during compilation: '-I /srv/LLVMsfw/linux/openmpi/1.10.2/include'
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT src/gtest_main.lo -MD -MP -MF src/.deps/gtest_main.Tpo -c src/gtest_main.cc -o src/gtest_main.o >/dev/null 2>&1
libtool: link: ar cru samples/.libs/libsamples.a samples/.libs/sample1.o samples/.libs/sample2.o samples/.libs/sample4.o 
libtool: link: ranlib samples/.libs/libsamples.a
libtool: link: ( cd "samples/.libs" && rm -f "libsamples.la" && ln -s "../libsamples.la" "libsamples.la" )
clang: warning: argument unused during compilation: '-I /srv/LLVMsfw/linux/openmpi/1.10.2/include'
libtool: compile:  ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -DOMPI_SKIP_MPICXX -DGTEST_HAS_PTHREAD=1 -Wall -MT src/gtest-all.lo -MD -MP -MF src/.deps/gtest-all.Tpo -c src/gtest-all.cc -o src/gtest-all.o >/dev/null 2>&1
/bin/bash ./libtool  --tag=CXX   --mode=link ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DGTEST_HAS_PTHREAD=1 -Wall   -o lib/libgtest.la -rpath /usr/local/lib src/gtest-all.lo  
libtool: link: ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx  -fPIC -DPIC -shared -nostdlib /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/crtbeginS.o  src/.libs/gtest-all.o   -Wl,-rpath -Wl,/srv/LLVMsfw/linux/openmpi/1.10.2/lib -Wl,-rpath -Wl,/srv/LLVMsfw/linux/openmpi/1.10.2/lib -L/srv/LLVMsfw/linux/openmpi/1.10.2/lib -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../.. -L/lib -L/usr/lib /srv/LLVMsfw/linux/openmpi/1.10.2/lib/libmpi_cxx.so /srv/LLVMsfw/linux/openmpi/1.10.2/lib/libmpi.so /srv/LLVMsfw/linux/openmpi/1.10.2/lib/libopen-rte.so /srv/LLVMsfw/linux/openmpi/1.10.2/lib/libopen-pal.so -ldl -lrt -lutil -lstdc++ -lm -lpthread -lc -lgcc_s /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/crtendS.o /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crtn.o    -pthread -Wl,-soname -Wl,libgtest.so.0 -o lib/.libs/libgtest.so.0.0.0
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
libtool: link: (cd "lib/.libs" && rm -f "libgtest.so.0" && ln -s "libgtest.so.0.0.0" "libgtest.so.0")
libtool: link: (cd "lib/.libs" && rm -f "libgtest.so" && ln -s "libgtest.so.0.0.0" "libgtest.so")
libtool: link: ar cru lib/.libs/libgtest.a  src/gtest-all.o
libtool: link: ranlib lib/.libs/libgtest.a
libtool: link: ( cd "lib/.libs" && rm -f "libgtest.la" && ln -s "../libgtest.la" "libgtest.la" )
/bin/bash ./libtool  --tag=CXX   --mode=link ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx -DGTEST_HAS_PTHREAD=1 -Wall   -o lib/libgtest_main.la -rpath /usr/local/lib src/gtest_main.lo lib/libgtest.la 
libtool: link: ccache /srv/LLVMsfw/linux/openmpi/1.10.2/bin/mpicxx  -fPIC -DPIC -shared -nostdlib /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/crtbeginS.o  src/.libs/gtest_main.o   -Wl,-rpath -Wl,/srv/jenkins_home/workspace/testFolder/DevOpTester/ibamr_pr_LLVM/ibtk/contrib/googletest/googletest/lib/.libs -Wl,-rpath -Wl,/srv/LLVMsfw/linux/openmpi/1.10.2/lib -Wl,-rpath -Wl,/srv/LLVMsfw/linux/openmpi/1.10.2/lib lib/.libs/libgtest.so -L/srv/LLVMsfw/linux/openmpi/1.10.2/lib -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../.. -L/lib -L/usr/lib /srv/LLVMsfw/linux/openmpi/1.10.2/lib/libmpi_cxx.so /srv/LLVMsfw/linux/openmpi/1.10.2/lib/libmpi.so /srv/LLVMsfw/linux/openmpi/1.10.2/lib/libopen-rte.so /srv/LLVMsfw/linux/openmpi/1.10.2/lib/libopen-pal.so -ldl -lrt -lutil -lstdc++ -lm -lpthread -lc -lgcc_s /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/crtendS.o /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crtn.o    -pthread -Wl,-soname -Wl,libgtest_main.so.0 -o lib/.libs/libgtest_main.so.0.0.0
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
libtool: link: (cd "lib/.libs" && rm -f "libgtest_main.so.0" && ln -s "libgtest_main.so.0.0.0" "libgtest_main.so.0")
libtool: link: (cd "lib/.libs" && rm -f "libgtest_main.so" && ln -s "libgtest_main.so.0.0.0" "libgtest_main.so")
libtool: link: ar cru lib/.libs/libgtest_main.a  src/gtest_main.o
libtool: link: ranlib lib/.libs/libgtest_main.a
libtool: link: ( cd "lib/.libs" && rm -f "libgtest_main.la" && ln -s "../libgtest_main.la" "libgtest_main.la" )
make[4]: Target `all' not remade because of errors.
make[4]: Leaving directory `/srv/jenkins_home/workspace/testFolder/DevOpTester/ibamr_pr_LLVM/ibtk/contrib/googletest/googletest'
make[4]: Entering directory `/srv/jenkins_home/workspace/testFolder/DevOpTester/ibamr_pr_LLVM/ibtk/contrib/googletest'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/srv/jenkins_home/workspace/testFolder/DevOpTester/ibamr_pr_LLVM/ibtk/contrib/googletest'
make[3]: *** [all-recursive] Error 1
make[3]: Target `all' not remade because of errors.
```

**Comment by boyceg** [comment]
In the googletest Makefile.am, the gtest library is specified here:

https://github.com/DevOpTester/IBAMR/blob/00030d1c693073e8f45941fb05fa1bfeb69f5b31/ibtk/contrib/googletest/googletest/Makefile.am#L182 <https://github.com/DevOpTester/IBAMR/blob/00030d1c693073e8f45941fb05fa1bfeb69f5b31/ibtk/contrib/googletest/googletest/Makefile.am#L182>

This is setting up a "libtool library" for gtest (libgtest.la). You probably can switch it to a static library by changing "lib_LTLIBRARIES" to "lib_LIBRARIES", "libgtest.la" to "libgtest.a", and "lib_gtest_la_SOURCES" to "src/gtest-all.cc".

I wonder if all of this is getting too complicated/fragile. For now, how about we just include very specific instructions on how to download/configure/compile gtest and how to link to it, and not bundle googletest within the repo?

**Comment by deleeke** [comment]
Yeah that sounds good to me.

I was able to modify the googletest Makefile and make it build only static libraries, but alas the VM build still was failing with the missing aclocal error. 

I will:
* Modify the m4 file so configure can accept --with-gtest=$GTEST_DIR but not revert to a bundled gtest. 
* Update the documentation back on the other branch that doesn't have the bundled googletest project.
* Build googletest on the VM with proper compilers, flags, etc, and get Jenkins to test it.

We could talk about some checks that could run more easily on HPC systems (where you've said proper cmake/libtool are sometimes hard to come by) that would ensure proper function/installation of IBAMR. 

I imagine most developers are not working day-to-day on HPC systems, so I hope this is not too big a barrier to using gtest in development.

**Comment by deleeke** [comment]
Abandoning this route for now...

**Pull request closed without merging**
