### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by deleeke**
@boyceg 

This is a first attempt at resolving the issue that we cannot have two definitions of main(). I am attempting to use some combination of preprocessor directives to make it when it is trying to compile the test applicaiton "test_ex0" that it uses the main() function from testex0.cpp, not main.cpp.

This doesn't work. "make examples" still creates a functioning main2d program, but "make check" exits with this error:

```
                                 ^
```

../../../../../IBAMR/examples/IBFE/explicit/ex0/testex0.cpp: In function ‘int main(int, char**)’:
../../../../../IBAMR/examples/IBFE/explicit/ex0/testex0.cpp:8:5: error: redefinition of ‘int main(int, char**)’
 int main( int argc, char*\* argv ) {
     ^
In file included from ../../../../../IBAMR/examples/IBFE/explicit/ex0/testex0.cpp:2:0:
../../../../../IBAMR/examples/IBFE/explicit/ex0/main.cpp:549:5: error: ‘int main(int, char*_)’ previously defined here
 int main(int argc, char_ argv[])
     ^
make[1]: **\* [test_ex0-testex0.o] Error 1
make[1]: Leaving directory `/home/deleeke/myIBAMRfork/ibamr-test/examples/IBFE/explicit/ex0'
make: **\* [check-am] Error 2

Do you have any insight on how to implement the #ifndef and #define statements correctly, or do you think there is an entirely different approach that would be better in the long term?

### CODE REVIEW

**Comment by deleeke** [comment]
Retest this please

**Comment by boyceg** [comment]
> On Jul 20, 2016, at 1:16 PM, deleeke notifications@github.com wrote:
> 
> @boyceg https://github.com/boyceg
> This is a first attempt at resolving the issue that we cannot have two definitions of main(). I am attempting to use some combination of preprocessor directives to make it when it is trying to compile the test applicaiton "test_ex0" that it uses the main() function from testex0.cpp, not main.cpp.
> 
> This doesn't work. "make examples" still creates a functioning main2d program, but "make check" exits with this error:
> 
> Here is one way to change the Makefile.am to build two different versions of the tester (in two separate executables):

## Process this file with automake to produce Makefile.in

include $(top_srcdir)/config/Make-rules

## Dimension-dependent testers

EXAMPLE_SOURCES = run_example.cpp
EXAMPLE_DRIVER_SOURCES = main.cpp
TESTER_DRIVER_SOURCES = tester.cpp

EXTRA_DIST = input2d input3d

EXTRA_PROGRAMS =
if LIBMESH_ENABLED
if SAMRAI2D_ENABLED
EXTRA_PROGRAMS += main2d test2d
endif
if SAMRAI3D_ENABLED
EXTRA_PROGRAMS += main3d test3d
endif
endif

main2d_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=2
main2d_LDADD = $(IBAMR_LDFLAGS) $(IBAMR2d_LIBS) $(IBAMR_LIBS)
main2d_SOURCES = $(EXAMPLE_SOURCES) $(EXAMPLE_DRIVER_SOURCES)

test2d_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=2
test2d_LDADD = $(IBAMR_LDFLAGS) $(IBAMR2d_LIBS) $(IBAMR_LIBS) 
test2d_SOURCES = $(EXAMPLE_SOURCES) $(TESTER_DRIVER_SOURCES)

main3d_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=3
main3d_LDADD = $(IBAMR_LDFLAGS) $(IBAMR3d_LIBS) $(IBAMR_LIBS)
main3d_SOURCES = $(SOURCES)

examples: $(EXTRA_PROGRAMS)
        if test "$(top_srcdir)" != "$(top_builddir)" ; then \
          cp -f $(srcdir)/input2d $(PWD) ; \
        fi ;

clean-local:
        rm -f $(EXTRA_PROGRAMS)
        if test "$(top_srcdir)" != "$(top_builddir)" ; then \
          rm -f $(builddir)/input2d ; \
        fi ;

This assumes that the bulk of the code you want to run is in a file named "run_example.cpp", and that you have two different "harnesses" that you want to use it with, one named "main.cpp" and the other named "tester.cpp".

You can further divide things up so that you have two different make targets, e.g. "examples" and "tests":

## Process this file with automake to produce Makefile.in

include $(top_srcdir)/config/Make-rules

## Dimension-dependent testers

EXAMPLE_SOURCES = run_example.cpp
EXAMPLE_DRIVER_SOURCES = main.cpp
TESTER_DRIVER_SOURCES = tester.cpp

EXTRA_DIST = input2d input3d

EXTRA_EXAMPLE_PROGRAMS =
EXTRA_TEST_PROGRAMS =
if LIBMESH_ENABLED
if SAMRAI2D_ENABLED
EXTRA_EXAMPLE_PROGRAMS += main2d
EXTRA_TEST_PROGRAMS += test2d
endif
if SAMRAI3D_ENABLED
EXTRA_EXAMPLE_PROGRAMS += main3d
EXTRA_TEST_PROGRAMS += test3d
endif
endif

main2d_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=2
main2d_LDADD = $(IBAMR_LDFLAGS) $(IBAMR2d_LIBS) $(IBAMR_LIBS)
main2d_SOURCES = $(EXAMPLE_SOURCES) $(EXAMPLE_DRIVER_SOURCES)

test2d_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=2
test2d_LDADD = $(IBAMR_LDFLAGS) $(IBAMR2d_LIBS) $(IBAMR_LIBS) 
test2d_SOURCES = $(EXAMPLE_SOURCES) $(TESTER_DRIVER_SOURCES)

main3d_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=3
main3d_LDADD = $(IBAMR_LDFLAGS) $(IBAMR3d_LIBS) $(IBAMR_LIBS)
main3d_SOURCES = $(SOURCES)

examples: $(EXTRA_EXAMPLE_PROGRAMS)
        if test "$(top_srcdir)" != "$(top_builddir)" ; then \
          cp -f $(srcdir)/input2d $(PWD) ; \
        fi ;

tests: $(EXTRA_TEST_PROGRAMS)
        if test "$(top_srcdir)" != "$(top_builddir)" ; then \
          cp -f $(srcdir)/input2d $(PWD) ; \
        fi ;

clean-local:
        rm -f $(EXTRA_PROGRAMS)
        if test "$(top_srcdir)" != "$(top_builddir)" ; then \
          rm -f $(builddir)/input2d ; \
        fi ;

(Note that I haven't tested these, and so there could be some typos --- hopefully this conveys the basic idea.)

**Comment by deleeke** [comment]
Note: in order to get these to compile you probably need to run ./bootstrap  in the top directory of your IBAMR repository and then run ./configure in the build directory with the option LDFLAGS="-lgtest"

These don't yet actually call runExample from main because I was running into issues with errors that looked like variations of:

"../../../../../IBAMR/examples/IBFE/explicit/ex0/example_main.cpp:7:28: error: cannot convert ‘char**_’ to ‘char_’ for argument ‘2’ to ‘bool runExample(int, char_)’
make: *_\* [main2d-example_main.o] Error 1"

or 

"In file included from ../../../../../IBAMR/examples/IBFE/explicit/ex0/example_main.cpp:1:0:
../../../../../IBAMR/examples/IBFE/explicit/ex0/example.cpp: In function ‘bool runExamples(int, char**_)’:
../../../../../IBAMR/examples/IBFE/explicit/ex0/example.cpp:129:32: error: no matching function for call to ‘libMesh::LibMeshInit::LibMeshInit(int&, char**_&)’
     LibMeshInit init(argc, argv);"

I need to mess around more with this pointer situation I suppose.

**Comment by boyceg** [comment]
> On Jul 23, 2016, at 2:01 AM, deleeke notifications@github.com wrote:
> 
> Note: in order to get these to compile you probably need to run ./bootstrap in the top directory of your IBAMR repository and then run ./configure in the build directory with the option LDFLAGS="-lgtest"
> 
> These don't yet actually call runExample from main because I was running into issues with errors that looked like variations of:
> 
> "../../../../../IBAMR/examples/IBFE/explicit/ex0/example_main.cpp:7:28: error: cannot convert ‘char*_’ to ‘char’ for argument ‘2’ to ‘bool runExample(int, char)’
> make: *_ [main2d-example_main.o] Error 1"
> 
> The run_example function should take the same arguments as main(), e.g.

```
bool run_example(int argc, char** argv)
```

> or
> 
> "In file included from ../../../../../IBAMR/examples/IBFE/explicit/ex0/example_main.cpp:1:0:
> ../../../../../IBAMR/examples/IBFE/explicit/ex0/example.cpp: In function ‘bool runExamples(int, char)’:
> ../../../../../IBAMR/examples/IBFE/explicit/ex0/example.cpp:129:32: error: no matching function for call to ‘libMesh::LibMeshInit::LibMeshInit(int&, char&)’
> LibMeshInit init(argc, argv);"
> 
> I need to mess around more with this pointer situation I suppose.
> 
> I think this will be fixed if you use the above argument list.

-- Boyce

**Comment by deleeke** [comment]
I followed some advice given in[ this thread](http://stackoverflow.com/questions/5260907/whats-the-way-to-access-argc-and-argv-inside-of-a-test-case-in-google-test-fram) to help solve my problem. So now it can run the example as normal with `./main2d input2d` as well as call runExample() from inside a test case. 

I am going to look into a way to be able to define the END_TIME with a commandline argument.

**Comment by deleeke** [comment]
retest this please 

(Attempting to save the console output from the Jenkins job to a file so I can then possibly publish it publicly -- thinking about using gh-pages)

**Comment by deleeke** [comment]
(attempted to fix path for xml output in jenkins)
retest this please

**Comment by deleeke** [comment]
retest this please

**Comment by deleeke** [comment]
retest this please

**Comment by deleeke** [comment]
@boyceg 

I've got a script that looks through the examples and sees if there is a test program and if there is, compiles it, and then runs both 2d and 3d cases. Right now I only have examples in IBFE/explicit/ex0 and IBFE/explicit/ex2. The tests work correctly in ex0 and are failing in ex2. 

```
************Running test3d************
Note: Google Test filter = *.3d
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from IBFE_ex2
[ RUN      ] IBFE_ex2.3d
*** Warning, This code is deprecated, and likely to be removed in future library versions! ./include/libmesh/auto_ptr.h, line 317, compiled Jul 13 2016 at 15:55:48 ***
ERROR: Unrecognized 2D element type.
Stack frames: 18
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::MeshTools::Generation::build_cube(libMesh::UnstructuredMesh&, unsigned int, unsigned int, unsigned int, double, double, double, double, double, double, libMesh::ElemType, bool)
3: libMesh::MeshTools::Generation::build_square(libMesh::UnstructuredMesh&, unsigned int, unsigned int, double, double, double, double, libMesh::ElemType, bool)
4: ./test2d() [0x43faab]
5: ./test2d() [0x443a2e]
6: ./test2d() [0x53c460]
7: ./test2d() [0x5374a2]
8: ./test2d() [0x5245eb]
9: ./test2d() [0x524d66]
10: ./test2d() [0x525326]
11: ./test2d() [0x529f80]
12: ./test2d() [0x53d9aa]
13: ./test2d() [0x5383ec]
14: ./test2d() [0x528d7d]
15: ./test2d() [0x43e508]
16: __libc_start_main
17: ./test2d() [0x43e389]
[0] ../LIBMESH/src/mesh/mesh_generation.C, line 564, compiled Jul 13 2016 at 16:04:31
unknown file: Failure
C++ exception with description "Error in libMesh internal logic" thrown in the test body.
[  FAILED  ] IBFE_ex2.3d (693 ms)
[----------] 1 test from IBFE_ex2 (694 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (694 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] IBFE_ex2.3d

 1 FAILED TEST
```

Does this provide enough information for debugging? Also see the full [console output](https://boycegvm01.castle.unc.edu/job/IBAMR/job/ibamr_pull_requests/95/console)  and [gui test result display](https://boycegvm01.castle.unc.edu/job/IBAMR/job/ibamr_pull_requests/) (these are on the VM -- you need to be on campus or VPN to access).

**Comment by boyceg** [comment]
> On Jul 28, 2016, at 7:35 PM, deleeke notifications@github.com wrote:
> 
> @boyceg https://github.com/boyceg
> I've got a script that looks through the examples and sees if there is a test program and if there is, compiles it, and then runs both 2d and 3d cases. Right now I only have examples in IBFE/explicit/ex0 and IBFE/explicit/ex2. The tests work correctly in ex0 and are failing in ex2.
> 
> ***********_Running test3d**_*********
> Note: Google Test filter = _.3d
> [==========] Running 1 test from 1 test case.
> [----------] Global test environment set-up.
> [----------] 1 test from IBFE_ex2
> [ RUN      ] IBFE_ex2.3d
> *_\* Warning, This code is deprecated, and likely to be removed in future library versions! ./include/libmesh/auto_ptr.h, line 317, compiled Jul 13 2016 at 15:55:48 ***
> ERROR: Unrecognized 2D element type.
> Stack frames: 18
> 0: libMesh::print_trace(std::ostream&)
> 1: libMesh::MacroFunctions::report_error(char const_, int, char const_, char const*)
> 2: libMesh::MeshTools::Generation::build_cube(libMesh::UnstructuredMesh&, unsigned int, unsigned int, unsigned int, double, double, double, double, double, double, libMesh::ElemType, bool)
> 3: libMesh::MeshTools::Generation::build_square(libMesh::UnstructuredMesh&, unsigned int, unsigned int, double, double, double, double, libMesh::ElemType, bool)
> 4: ./test2d() [0x43faab]
> 5: ./test2d() [0x443a2e]
> 6: ./test2d() [0x53c460]
> 7: ./test2d() [0x5374a2]
> 8: ./test2d() [0x5245eb]
> 9: ./test2d() [0x524d66]
> 10: ./test2d() [0x525326]
> 11: ./test2d() [0x529f80]
> 12: ./test2d() [0x53d9aa]
> 13: ./test2d() [0x5383ec]
> 14: ./test2d() [0x528d7d]
> 15: ./test2d() [0x43e508]
> 16: __libc_start_main
> 17: ./test2d() [0x43e389]
> [0] ../LIBMESH/src/mesh/mesh_generation.C, line 564, compiled Jul 13 2016 at 16:04:31
> unknown file: Failure
> C++ exception with description "Error in libMesh internal logic" thrown in the test body.
> [  FAILED  ] IBFE_ex2.3d (693 ms)
> [----------] 1 test from IBFE_ex2 (694 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 1 test from 1 test case ran. (694 ms total)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] IBFE_ex2.3d
> 
>  1 FAILED TEST
> Does this provide enough information for debugging? Also see the full console output https://boycegvm01.castle.unc.edu/job/IBAMR/job/ibamr_pull_requests/95/console and gui test result display https://boycegvm01.castle.unc.edu/job/IBAMR/job/ibamr_pull_requests/ (these are on the VM -- you need to be on campus or VPN to access).
> 
> From the console output, it looks like the 2D test is working but reporting that it is failing.

For the 3D case, are you using the same input file as the 2D case?

**Comment by deleeke** [comment]
@boyceg 

Indeed I did have some mix up with the test3d input files, and I didn't have the bool runExample function returning the correct value in the ex2.cpp. So now the 2d case is running correctly in ex2, but I'm getting this memory leak error in the 3d case:

```
************Running test3d************
Note: Google Test filter = *.3d
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from IBFE_ex2
[ RUN      ] IBFE_ex2.3d
*** Warning, This code is deprecated, and likely to be removed in future library versions! ./include/libmesh/auto_ptr.h, line 317, compiled Jul 13 2016 at 15:55:48 ***
IBFEMethod: using FIRST order LAGRANGE finite elements.

*** Warning, This code is deprecated, and likely to be removed in future library versions! ../LIBMESH/src/mesh/boundary_info.C, line 1205, compiled Jul 13 2016 at 16:02:59 ***

Writing visualization files...

+++++++++++++++++++++++++++++++++++++++++++++++++++
At beginning of timestep # 0
Simulation time is 0
Assertion `i < this->n_sides()' failed.
i = 0
this->n_sides() = 0


Stack frames: 24
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::Quad4::build_side_ptr(unsigned int, bool)
3: libMesh::Face::build_edge_ptr(unsigned int)
4: ./test3d() [0xb4cbc1]
5: ./test3d() [0xb4d7e4]
6: ./test3d() [0x7ccb56]
7: ./test3d() [0x7ced65]
8: ./test3d() [0x590238]
9: ./test3d() [0xaf355d]
10: ./test3d() [0x442146]
11: ./test3d() [0x443ce4]
12: ./test3d() [0x54454c]
13: ./test3d() [0x53f58e]
14: ./test3d() [0x52c6d7]
15: ./test3d() [0x52ce52]
16: ./test3d() [0x52d412]
17: ./test3d() [0x53206c]
18: ./test3d() [0x545a96]
19: ./test3d() [0x5404d8]
20: ./test3d() [0x530e69]
21: ./test3d() [0x43e688]
22: __libc_start_main
23: ./test3d() [0x43e509]
[0] ../LIBMESH/src/geom/face_quad4.C, line 130, compiled Jul 13 2016 at 16:02:17

 ---------------------------------------------------------------------------- 
| Reference count information                                                |
 ---------------------------------------------------------------------------- 
| N7libMesh10FEAbstractE reference count information:
|  Creations:    77
|  Destructions: 77
| N7libMesh10Parameters5ValueE reference count information:
|  Creations:    2
|  Destructions: 2
| N7libMesh12LinearSolverIdEE reference count information:
|  Creations:    1
|  Destructions: 0
| N7libMesh12SparseMatrixIdEE reference count information:
|  Creations:    1
|  Destructions: 0
| N7libMesh13NumericVectorIdEE reference count information:
|  Creations:    38
|  Destructions: 32
| N7libMesh15EquationSystemsE reference count information:
|  Creations:    1
|  Destructions: 1
| N7libMesh4ElemE reference count information:
|  Creations:    472578
|  Destructions: 472578
| N7libMesh4NodeE reference count information:
|  Creations:    5445
|  Destructions: 5445
| N7libMesh5QBaseE reference count information:
|  Creations:    88
|  Destructions: 88
| N7libMesh6DofMapE reference count information:
|  Creations:    4
|  Destructions: 4
| N7libMesh6SystemE reference count information:
|  Creations:    4
|  Destructions: 4
| N7libMesh9DofObjectE reference count information:
|  Creations:    516187
|  Destructions: 516187
 ---------------------------------------------------------------------------- 
Memory leak detected!
unknown file: Failure
C++ exception with description "Error in libMesh internal logic" thrown in the test body.
[  FAILED  ] IBFE_ex2.3d (52345 ms)
[----------] 1 test from IBFE_ex2 (52345 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (52345 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] IBFE_ex2.3d

 1 FAILED TEST
```

Does that seem like a valid reason for the test to fail?
I am trying to get a handle on what a valid test looks like before I start doing this for many examples.

**Pull request closed without merging**
